### ISSUE TITLE
[Bug]: Issue with arclight

### ISSUE THREAD

**Issue by marcellonovak** [Fuzss/easyanvils#52]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.19.2 - forge 43.3.7 /  Version 角 (Horn) / arclight-1.19.2-1.0.4-4dbbff1

### Mod Version(s) (Required)

EasyAnvils-v4.0.11-1.19.2-Forge

### Other Mods Involved (Required)

Yes

### Notes (Required)

For some reason, I can't take items out of the anvil after renaming them, and I get this massive error:
this happens even if the only things installed on the arclight server are just easyanvils
```
[14Mar2024 22:46:37.378] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@7ef810dd, suppressing error
java.lang.NullPointerException: Cannot invoke "io.izzel.arclight.common.bridge.core.world.WorldBridge.bridge$getWorld()" because the return value of "io.izzel.arclight.common.bridge.core.util.IWorldPosCallableBridge.bridge$getWorld()" is null
	at io.izzel.arclight.common.bridge.core.util.IWorldPosCallableBridge.bridge$getLocation(IWorldPosCallableBridge.java:21) ~[arclight-1.19.2-1.0.4-4dbbff1.jar%23262!/:arclight-1.19.2-1.0.4-4dbbff1] {re:mixin,re:classloading}
	at net.minecraft.world.inventory.AnvilMenu.getBukkitView(RepairContainerMixin.java:739) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.RepairContainerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.AnvilMenuAccessor,pl:mixin:A}
	at net.minecraft.world.inventory.AnvilMenu.m_6640_(RepairContainerMixin.java:563) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.RepairContainerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.AnvilMenuAccessor,pl:mixin:A}
	at net.minecraft.world.inventory.ItemCombinerMenu.m_6199_(ItemCombinerMixin.java:80) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.ItemCombinerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.ItemCombinerMenuAccessor,pl:mixin:A}
	at net.minecraft.world.inventory.ItemCombinerMenu$1.m_6596_(ItemCombinerMenu.java:26) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:classloading}
	at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainerMixin.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at fuzs.easyanvils.world.inventory.BuiltInAnvilMenu.init(BuiltInAnvilMenu.java:16) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23302!/:4.0.11] {re:classloading}
	at fuzs.easyanvils.world.inventory.ModAnvilMenu.m_6640_(ModAnvilMenu.java:88) ~[EasyAnvils-v4.0.11-1.19.2-Forge.jar%23302!/:4.0.11] {re:mixin,re:classloading}
	at net.minecraft.world.inventory.ItemCombinerMenu.m_6199_(ItemCombinerMixin.java:80) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.inventory.ItemCombinerMixin,pl:mixin:APP:easyanvils.common.mixins.json:accessor.ItemCombinerMenuAccessor,pl:mixin:A}
	at net.minecraft.world.level.block.AnvilBlock.handler$zze000$easyanvils$use(AnvilBlock.java:541) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,re:classloading,pl:mixin:APP:easyanvils.common.mixins.json:AnvilBlockMixin,pl:mixin:APP:placebo.mixins.json:AnvilBlockMixin,pl:mixin:A}
	at net.minecraft.world.level.block.AnvilBlock.m_6227_(AnvilBlock.java) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,re:classloading,pl:mixin:APP:easyanvils.common.mixins.json:AnvilBlockMixin,pl:mixin:APP:placebo.mixins.json:AnvilBlockMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour_BlockStateBaseMixin.java:714) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.block.state.BlockBehaviour_BlockStateBaseMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:APP:lootr.mixins.json:MixinBlockStateBase,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameModeMixin.java:838) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.management.ServerPlayerGameModeMixin,pl:mixin:APP:mixins.artifacts.json:item.diggingclaws.ServerPlayerGameModeMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:realtime.PlayerInteractionManagerMixin_Realtime,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerPlayNetHandlerMixin.java:1060) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.ServerGamePacketListenerImplMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:34) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CPlayerTryUseItemOnBlockPacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(CPlayerTryUseItemOnBlockPacketMixin.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CPlayerTryUseItemOnBlockPacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.PacketUtils.md5efe9d$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2131) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23365!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
```

### latest.log (Required)

https://gist.github.com/marcellonovak/47fd4499960245faa1f1eb885d72b51f

**Comment by Fuzss** [comment]
Seems to not be compatible with Arclight then. Nothing I'll do about it.
